# Generated by Django 5.1.6 on 2025-03-03 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='链接名称')),
                ('url', models.URLField(verbose_name='链接地址')),
                ('logo', models.ImageField(blank=True, upload_to='links/', verbose_name='链接Logo')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='链接描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='网站标题')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='网站副标题')),
                ('description', models.TextField(blank=True, verbose_name='网站描述')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='网站关键词')),
                ('logo', models.ImageField(blank=True, upload_to='site/', verbose_name='网站Logo')),
                ('favicon', models.ImageField(blank=True, upload_to='site/', verbose_name='网站图标')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('weibo', models.URLField(blank=True, verbose_name='微博')),
                ('icp', models.CharField(blank=True, max_length=30, verbose_name='ICP备案号')),
                ('analytics_code', models.TextField(blank=True, verbose_name='统计代码')),
                ('footer_info', models.TextField(blank=True, verbose_name='底部信息')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '站点设置',
                'verbose_name_plural': '站点设置',
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-is_pinned', '-published_at'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='blog.category', verbose_name='父分类'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='post',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='允许评论'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_html',
            field=models.TextField(blank=True, verbose_name='HTML内容'),
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.category', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='post',
            name='comments_count',
            field=models.PositiveIntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta描述'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta关键词'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/%Y/%m', verbose_name='头像')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='个人简介')),
                ('website', models.URLField(blank=True, verbose_name='个人网站')),
                ('location', models.CharField(blank=True, max_length=50, verbose_name='所在地')),
                ('github', models.CharField(blank=True, max_length=255, verbose_name='GitHub')),
                ('twitter', models.CharField(blank=True, max_length=255, verbose_name='Twitter')),
                ('weibo', models.CharField(blank=True, max_length=255, verbose_name='微博')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
    ]
