# This is a basic workflow to help you get started with Actions

name: MyBlog

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  #pull_request:
   # branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: SSH 登录服务器并执行部署
        uses: appleboy/ssh-action@master
        with:
          host: ${{ 123.56.118.72 }}
          username: ${{ root }}
          password: ${{ 1310195396Tsy }}
          script: |
            cd ~/blog
            git pull origin main
            docker-compose down
            docker-compose up -d --build
