name: Deploy Backend

on:
  push:
    branches: [ main, master ]
    paths:
      - 'backend/**'  # 仅后端代码更新时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Server (Build on Server)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}          # 例如：123.56.118.72
          username: ${{ secrets.SERVER_NAME }}      # 服务器登录用户名
          password: ${{ secrets.SERVER_PASSWORD }}      # 服务器登录密码
          script: |
            # 进入项目所在目录（请根据实际路径调整）
            cd ~/blog/backend
            
            # 拉取最新代码
            git pull origin main
            
            # 构建 Docker 镜像（使用仓库中的 Dockerfile）
            docker build -t myblog-backend .
            
            # 如果已有容器，停止并删除
            docker stop myblog-backend || true
            docker rm myblog-backend || true

            echo "Docker image built successfully!!!"
            
            # 启动新容器
            docker run -d --name myblog-backend \
              -p 8000:8000 \
              -v /var/www/staticfiles:/app/staticfiles \
              -v /var/www/media:/app/media \
              --restart unless-stopped \
              myblog-backend
            
            # 执行数据库迁移
            docker exec myblog-backend python manage.py migrate || { echo "Migration failed"; exit 1; }
            
            # 生成静态文件
            docker exec myblog-backend python manage.py collectstatic --noinput || { echo "Collectstatic failed"; exit 1; }
